/**
 * Config for test environment is pretty different from dev and prod, so we don't use common config as base.
 *
 * Karma watches the test entry points, so we don't need to define entry point here.
 */
module.exports = {
    /**
     * Inline source maps, generated by TypeScript compiler, will be used for code coverage.
     */
    devtool: 'inline-source-map',

    verbose: true,

    resolve: {
        extensions: ['', '.ts', '.js', '.scss', '.html'],
        modulesDirectories: ['node_modules', 'src']
    },

    module: {
        loaders: [
            /**
             * Enable inline source maps for code coverage report.
             *
             * See info about loaders in dev config.
             */
            {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader?' + JSON.stringify({
                        sourceMap: false,
                        inlineSourceMap: true
                    }),
                    'angular2-template-loader'
                ]
            },
            /**
             * These loaders are used in other environments as well, see `webpack.config.common.js`.
             */
            {test: /\.json$/, loader: 'json-loader'},
            {test: /\.html$/, loader: 'raw-loader'},
            {test: /\.scss$/, loaders: ['raw-loader', 'sass-loader']}
        ],
        postLoaders: [
            /**
             * Instruments TS source files for subsequent code coverage.
             * See https://github.com/deepsweet/istanbul-instrumenter-loader
             */
            {
                test: /\.ts$/,
                loader: 'istanbul-instrumenter-loader',
                exclude: [
                    'node_modules',
                    /\.(e2e|spec)\.ts$/
                ]
            }
        ]
    }
};
