/**
 * Config for test environment is pretty different from dev and prod, so we don't use common config as base.
 */
module.exports = {
    /**
     * Inline source maps, generated by TypeScript compiler, will be used.
     */
    devtool: 'inline-source-map',

    /**
     * Entry point / test environment builder is also written in TypeScript.
     */
    entry: './tests/main.ts',

    verbose: true,

    resolve: {
        extensions: ['', '.ts', '.js']
    },

    module: {
        preLoaders: [
            /**
             * Lint TypeScript before loading it.
             * See https://github.com/wbuchwalter/tslint-loader for details.
             */
            {
                test: /\.ts$/,
                loader: 'tslint-loader',
                exclude: ['node_modules']
            }
        ],
        loaders: [
            /**
             * Unlike ts-loader, awesome-typescript-loader doesn't allow to override TS compiler options
             * in query params. We use separate `tsconfig.test.json` file, which only differs in one thing:
             * inline source maps. They are used for code coverage report.
             *
             * See project repository for details / configuration reference:
             * https://github.com/s-panferov/awesome-typescript-loader
             */
            {
                test: /\.ts$/,
                loader: 'awesome-typescript-loader',
                query: {
                    tsconfig: 'tsconfig.test.json'
                }
            },
            /**
             * These loaders are used in other environments as well.
             */
            { test: /\.json$/, loader: 'json-loader' },
            { test: /\.html$/, loader: 'html-loader' },
            { test: /\.scss$/, loader: 'to-string-loader!css-loader!sass-loader' }
        ],
        postLoaders: [
            /**
             * Instruments TS source files for subsequent code coverage.
             * See https://github.com/deepsweet/istanbul-instrumenter-loader
             */
            {
                test: /\.ts$/,
                loader: 'istanbul-instrumenter-loader',
                exclude: [
                    /node_modules/,
                    /tests/,
                    /\.(e2e|spec)\.ts$/
                ]
            }
        ]
    }
};
